[project]
name = "contact-energy-ha-integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "contact-energy-nz>=0.1.20878578945",
    "fastapi>=0.128.0",
    "pydantic>=2.12.5",
]
